language: python
sudo: required
# https://docs.travis-ci.com/user/ci-environment/ to get a modern gcc etc
dist: trusty


# notes from http://conda.pydata.org/docs/travis.html
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
install:
  #  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 50
  # - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50
  # We do this conditionally because it saves us some downloading if the
  # version is the same. 
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - gcc --version
  - export CC=/usr/bin/gcc-5
  - export CXX=/usr/bin/g++-5
  - $CXX --version
  - printenv
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numba pytest cython nose
  - source activate test-environment
  - pip install pyfftw
  - pip install git+https://github.com/ericmjonas/eigency.git
  - $CC --version
  - DISTUTILS_DEBUG=1 python setup.py install
  - ls /home/travis/miniconda/envs/test-environment/lib/python2.7/site-packages/chirpz

script:
  # Your test script goes here
  cd tests && nosetests

addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    packages:
    # install toolchains
    - gcc-5
    - g++-5
    - libfftw3-dev
    - libboost-dev
    - libeigen3-dev
    - libboost-system-dev
    - libboost-timer-dev
    - libboost-system1.54.0
    - libboost-timer1.54.0
