version: 2.1

orbs:
  python: circleci/python@0.2.1

commands:
  preinstall:
    description:  "Set up system-level packages"
    steps:
      - run:
          name: install linux packages
          command: |
            sudo apt-get update
            
            sudo apt-get -yq install libfftw3-dev libboost-dev libeigen3-dev g++ libboost-system-dev libboost-timer-dev libboost-system libboost-timer
            
jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - preinstall
      #- python/load-cache
      #- python/install-deps
      #- python/save-cache
      - run:
          #command: ./manage.py test
          command: echo "hello world"
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
